### PR TITLE
Scheduler verbosity

### PR DESCRIPTION
**Pull request by cturbelin**
Increase scheduler verbosity on startup and add warning if no instance is registered (fool-proof).

### CODE REVIEW

**Comment by phev8** [comment]
Very good, thank you!
Recently, we were wondering, if it would be better to use a different word / attribute name instead of `frequency`, just to avoid confusion, if the value is to be understood as real frequency (where in fact it is period / time between to occurrences). 
Regarding this, I wanted to ask if you think, a small rewording of the log lines would be better right now? 

E.g., `...Printf("Starting loop for %s with a period of %s", loopName, durationBetween)`
This would also print the duration with human readable format, I believe, assuming durationBetween is a duration object (probably should convert to it if not already one...) - so a small utility method that receive the "freq" and "name" and does the printing is probably justified. We are about to add two new loops (for researcher-notifications and participant-messages) - and if something is used at so many places, probably better to centralise it.

**Comment by phev8** [comment]
For the "instances" logic: how about removing the "warning", and rather move the check of for the length into the `GetAllInstances` method. If there are no instances, it could return an error, which get's printed anyway. 
Like question is, is it ever a valid use-case if there are no "instances" defined - if the answer is not, semantically "error" classification is probably fine. 

ERROR prefix can be used to eventually trigger automated reporting to admin, and ERROR indicates something that went wrong, when it should not have gone wrong, and something that needs active attention of the admin. 
WARNING is just something the might be wrong or unintentional. So if this is something, that needs immediate attention to be fixed, ERROR is well justified, and putting the logic either in the `GetAllInstances` or a small wrapper method, makes code simpler / reusable. 
What do you think?

**Comment by cturbelin** [comment]
I think you're right. If instance definition is the foundation of the system (and nothing can work correctly outside an instance) then,   the no instance defined situation should raise an error.
Then I can rework to put the check in getAllInstances(), and maybe add a check on service startup ? (should we run the services before the globalDB to be configured ?

**Comment by phev8** [comment]
I think, it's enough to keep the check in the loop. Though most common error would be that the collection is not initialised at all at the beginning, but in theory it can also change while the service is running (e.g., somehow it's deleted, renamed, emptied). If not initialised, it would raise error at first attempt (which I believe happens immediately at start?), but then later as well, if for any reason the DB content changed.

**Pull request merged**
